using System;
using System.Collections.Generic;
using System.Linq;

namespace KJX.Scripting.Codegen;

/// <summary>
/// Writes the dispatch tables: one switch per interface with typed argument extraction, and a set
/// of readers and writers for the DTOs, enums, collections and references those members use.
/// Nothing on this path binds an argument by reflection, which is what keeps it trim-safe.
/// </summary>
internal sealed partial class DispatchEmitter
{
    private const string Header = """
        // <auto-generated>
        //     Generated by KJX.Scripting.Codegen from the [ScriptApi] interfaces in this project.
        //     Edits are lost on the next build. Change the interface instead.
        // </auto-generated>
        #nullable disable
        #pragma warning disable CS1998 // async member without await: some members are synchronous
        """;

    private static readonly string[] Usings =
    {
        "using System;",
        "using System.Collections.Generic;",
        "using System.Runtime.CompilerServices;",
        "using System.Text.Json;",
        "using System.Text.Json.Nodes;",
        "using System.Threading;",
        "using System.Threading.Tasks;",
        "using KJX.Scripting.Runtime;",
    };

    private readonly ApiModel _model;
    private readonly Dictionary<string, ApiDto> _dtos;
    private readonly Dictionary<string, ApiEnum> _enums;
    private readonly SortedDictionary<string, string> _helpers = new(StringComparer.Ordinal);
    private readonly HashSet<string> _started = new(StringComparer.Ordinal);

    private DispatchEmitter(ApiModel model)
    {
        _model = model;
        _dtos = model.Dtos.ToDictionary(dto => dto.Name, StringComparer.Ordinal);
        _enums = model.Enums.ToDictionary(item => item.Name, StringComparer.Ordinal);
    }

    /// <summary>Produces every generated file for the model, keyed by hint name.</summary>
    public static IEnumerable<(string HintName, string Source)> Emit(ApiModel model)
    {
        var emitter = new DispatchEmitter(model);
        var files = new List<(string, string)>();

        // Dispatchers first: emitting them is what discovers the readers and writers needed.
        foreach (var type in model.Types)
            files.Add(($"{type.DispatcherName}.g.cs", emitter.EmitDispatcher(type)));

        files.Add(("ScriptApiValues.g.cs", emitter.EmitValues()));
        files.Add(("ScriptApiRegistry.g.cs", emitter.EmitRegistry()));

        return files;
    }

    private string EmitDispatcher(ApiType type)
    {
        var code = StartFile();

        code.Doc(type.Doc ?? $"Dispatch for {type.Clr}.");
        using (code.Block($"internal sealed class {type.DispatcherName} : IScriptApiDispatcher"))
        {
            code.Line($"internal static readonly {type.DispatcherName} Instance = new {type.DispatcherName}();");
            code.Line();
            code.Line($"private static readonly string[] MemberNamesValue = {{ {Names(type.Members.Select(m => m.Name))} }};");
            code.Line($"private static readonly string[] ExtendsValue = {{ {Names(type.Extends)} }};");
            code.Line();
            code.Line($"public string WireTypeName => {JsonText.CSharpLiteral(type.Name)};");
            code.Line($"public Type TargetType => typeof({type.Clr});");
            code.Line("public IReadOnlyList<string> Extends => ExtendsValue;");
            code.Line("public IReadOnlyList<string> MemberNames => MemberNamesValue;");
            code.Line();

            EmitMemberKinds(code, type);
            code.Line();
            EmitInvoke(code, type);
            code.Line();
            EmitSubscribe(code, type);

            foreach (var member in type.Members.Where(m => m.Kind == ApiMemberKind.Stream))
            {
                code.Line();
                EmitStreamMethod(code, type, member);
            }
        }

        return FinishFile(code);
    }

    private static void EmitMemberKinds(CodeBuilder code, ApiType type)
    {
        using (code.Block("public bool TryGetMemberKind(string member, out ScriptApiMemberKind kind)"))
        using (code.Block("switch (member)"))
        {
            foreach (var group in type.Members.GroupBy(IsStream).OrderBy(g => g.Key))
            {
                foreach (var member in group)
                    code.Line($"case {JsonText.CSharpLiteral(member.Name)}:");

                code.Indent();
                code.Line($"kind = ScriptApiMemberKind.{(group.Key ? "Stream" : "Call")};");
                code.Line("return true;");
                code.Outdent();
            }

            code.Line("default:");
            code.Indent();
            code.Line("kind = default;");
            code.Line("return false;");
            code.Outdent();
        }
    }

    private void EmitInvoke(CodeBuilder code, ApiType type)
    {
        using (code.Block(
                   "public async ValueTask<JsonNode> InvokeAsync(object target, string member, JsonElement arguments, " +
                   "IScriptApiReferences references, CancellationToken cancellationToken)"))
        {
            if (type.Members.Count > 0)
                code.Line($"var instance = ({type.Clr})target;");

            using (code.Block("switch (member)"))
            {
                foreach (var member in type.Members.Where(m => m.Kind != ApiMemberKind.Stream))
                {
                    code.Line($"case {JsonText.CSharpLiteral(member.Name)}:");
                    using (code.Block(string.Empty))
                        EmitCall(code, type, member);
                }

                foreach (var member in type.Members.Where(IsStream))
                {
                    code.Line($"case {JsonText.CSharpLiteral(member.Name)}:");
                    code.Indent();
                    code.Line($"throw ScriptApiException.WrongMemberKind({JsonText.CSharpLiteral(type.Name)}, member, \"a call\");");
                    code.Outdent();
                }

                code.Line("default:");
                code.Indent();
                code.Line($"throw ScriptApiException.MemberNotFound({JsonText.CSharpLiteral(type.Name)}, member);");
                code.Outdent();
            }
        }
    }

    private void EmitCall(CodeBuilder code, ApiType type, ApiMember member)
    {
        var qualified = JsonText.CSharpLiteral($"{type.Name}.{member.Name}");
        var arguments = BindArguments(code, member, qualified);

        switch (member.Kind)
        {
            case ApiMemberKind.Get:
                code.Line($"var result = instance.{member.ClrName};");
                code.Line($"return {WriteValue(member.Returns, "result")};");
                return;

            case ApiMemberKind.Set:
                code.Line($"instance.{member.ClrName} = {arguments[0]};");
                code.Line("return null;");
                return;

            default:
                var call = $"instance.{member.ClrName}({string.Join(", ", CallArguments(member, arguments))})";
                if (member.IsAwaitable)
                    call = $"await {call}.ConfigureAwait(false)";

                if (member.Returns == null)
                {
                    code.Line($"{call};");
                    code.Line("return null;");
                }
                else
                {
                    code.Line($"var result = {call};");
                    code.Line($"return {WriteValue(member.Returns, "result")};");
                }

                return;
        }
    }

    /// <summary>
    /// Emits the statements that bind each declared parameter to a local, and returns the local
    /// names. Optional parameters fall back to the default written on the C# signature.
    /// </summary>
    private List<string> BindArguments(CodeBuilder code, ApiMember member, string qualifiedMember)
    {
        var locals = new List<string>();

        for (var i = 0; i < member.Parameters.Count; i++)
        {
            var parameter = member.Parameters[i];
            var literal = JsonText.CSharpLiteral(parameter.Name);
            var element = $"element{i}";
            var local = $"argument{i}";

            if (parameter.HasDefault)
            {
                var read = ReadValue(parameter.Type, element, literal, qualifiedMember);
                code.Line($"var {local} = ScriptApiJson.TryGet(arguments, {literal}, {qualifiedMember}, out var {element})");
                code.Indent();
                code.Line($"? {read}");
                code.Line($": {parameter.DefaultExpression};");
                code.Outdent();
            }
            else
            {
                code.Line($"var {element} = ScriptApiJson.Required(arguments, {literal}, {qualifiedMember});");
                code.Line($"var {local} = {ReadValue(parameter.Type, element, literal, qualifiedMember)};");
            }

            locals.Add(local);
        }

        return locals;
    }

    private static IEnumerable<string> CallArguments(ApiMember member, IReadOnlyList<string> locals)
    {
        foreach (var local in locals)
            yield return local;

        if (member.PassesCancellationToken)
            yield return "cancellationToken";
    }

    private void EmitSubscribe(CodeBuilder code, ApiType type)
    {
        using (code.Block(
                   "public IAsyncEnumerable<JsonNode> Subscribe(object target, string member, JsonElement arguments, " +
                   "IScriptApiReferences references, CancellationToken cancellationToken)"))
        {
            var streams = type.Members.Where(IsStream).ToList();

            if (streams.Count > 0)
                code.Line($"var instance = ({type.Clr})target;");

            using (code.Block("switch (member)"))
            {
                foreach (var member in streams)
                {
                    code.Line($"case {JsonText.CSharpLiteral(member.Name)}:");
                    code.Indent();
                    code.Line($"return {StreamMethodName(member)}(instance, arguments, references, cancellationToken);");
                    code.Outdent();
                }

                foreach (var member in type.Members.Where(m => !IsStream(m)))
                {
                    code.Line($"case {JsonText.CSharpLiteral(member.Name)}:");
                    code.Indent();
                    code.Line($"throw ScriptApiException.WrongMemberKind({JsonText.CSharpLiteral(type.Name)}, member, \"a stream\");");
                    code.Outdent();
                }

                code.Line("default:");
                code.Indent();
                code.Line($"throw ScriptApiException.MemberNotFound({JsonText.CSharpLiteral(type.Name)}, member);");
                code.Outdent();
            }
        }
    }

    private void EmitStreamMethod(CodeBuilder code, ApiType type, ApiMember member)
    {
        var qualified = JsonText.CSharpLiteral($"{type.Name}.{member.Name}");

        using (code.Block(
                   $"private static async IAsyncEnumerable<JsonNode> {StreamMethodName(member)}({type.Clr} instance, " +
                   "JsonElement arguments, IScriptApiReferences references, " +
                   "[EnumeratorCancellation] CancellationToken cancellationToken)"))
        {
            var locals = BindArguments(code, member, qualified);

            string source;
            if (member.Parameters.Count == 0 && !member.PassesCancellationToken && !member.IsAwaitable)
            {
                // A property, or a method that does not take the token: cancel from the outside.
                source = $"instance.{member.ClrName}{(member.FromProperty ? string.Empty : "()")}.WithCancellation(cancellationToken)";
            }
            else
            {
                var call = $"instance.{member.ClrName}({string.Join(", ", CallArguments(member, locals))})";
                if (member.IsAwaitable)
                {
                    code.Line($"var stream = await {call}.ConfigureAwait(false);");
                    call = "stream";
                }

                source = member.PassesCancellationToken ? call : $"{call}.WithCancellation(cancellationToken)";
            }

            using (code.Block($"await foreach (var item in {source}.ConfigureAwait(false))"))
                code.Line($"yield return {WriteValue(member.Returns, "item")};");
        }
    }

    private static bool IsStream(ApiMember member) => member.Kind == ApiMemberKind.Stream;

    private static string StreamMethodName(ApiMember member) => "Stream" + Identifier(member.Name);

    private string EmitRegistry()
    {
        var code = StartFile();

        code.Doc("Everything this assembly exposes to scripts: the descriptor and the dispatch tables.");
        using (code.Block("public static class ScriptApiRegistry"))
        {
            code.Line("private static readonly IScriptApiDispatcher[] DispatchersValue =");
            code.Line("{");
            code.Indent();
            foreach (var type in _model.Types)
                code.Line($"{type.DispatcherName}.Instance,");
            code.Outdent();
            code.Line("};");
            code.Line();

            code.Doc("The full API descriptor as JSON.");
            code.Line("public static string DescriptorJson => ScriptApiDescriptor.Json;");
            code.Line();
            code.Doc("The content hash of the descriptor.");
            code.Line("public static string DescriptorHash => ScriptApiDescriptor.Hash;");
            code.Line();
            code.Doc("Every dispatch table in this assembly.");
            code.Line("public static IReadOnlyList<IScriptApiDispatcher> Dispatchers => DispatchersValue;");
            code.Line();

            code.Doc("Finds the dispatcher for a wire type name.");
            using (code.Block("public static bool TryGetType(string wireTypeName, out IScriptApiDispatcher dispatcher)"))
            {
                using (code.Block("foreach (var candidate in DispatchersValue)"))
                using (code.Block("if (candidate.WireTypeName == wireTypeName)"))
                {
                    code.Line("dispatcher = candidate;");
                    code.Line("return true;");
                }

                code.Line();
                code.Line("dispatcher = null;");
                code.Line("return false;");
            }

            code.Line();
            code.Doc("Finds the dispatcher that owns a member, following inherited script API types.");
            using (code.Block(
                       "public static bool TryGetMember(string wireTypeName, string member, " +
                       "out IScriptApiDispatcher dispatcher, out ScriptApiMemberKind kind)"))
            {
                code.Line("kind = default;");
                code.Line();
                using (code.Block("if (!TryGetType(wireTypeName, out dispatcher))"))
                    code.Line("return false;");

                code.Line();
                using (code.Block("if (dispatcher.TryGetMemberKind(member, out kind))"))
                    code.Line("return true;");

                code.Line();
                using (code.Block("foreach (var inherited in dispatcher.Extends)"))
                using (code.Block("if (TryGetMember(inherited, member, out dispatcher, out kind))"))
                    code.Line("return true;");

                code.Line();
                code.Line("dispatcher = null;");
                code.Line("return false;");
            }
        }

        return FinishFile(code);
    }

    private string EmitValues()
    {
        var code = StartFile();

        code.Doc("Readers and writers for the values that cross the script boundary.");
        using (code.Block("internal static class ScriptApiValues"))
        {
            var first = true;
            foreach (var helper in _helpers.Values)
            {
                if (!first)
                    code.Line();

                first = false;
                foreach (var line in helper.TrimEnd('\n').Split('\n'))
                    code.Line(line);
            }
        }

        return FinishFile(code);
    }

    private CodeBuilder StartFile()
    {
        var code = new CodeBuilder();
        foreach (var line in Header.Split('\n'))
            code.Line(line);

        code.Line();
        foreach (var line in Usings)
            code.Line(line);

        code.Line();
        code.Open($"namespace {_model.GeneratedNamespace}");
        return code;
    }

    private static string FinishFile(CodeBuilder code)
    {
        code.Close();
        return code.ToString();
    }

    private static string Names(IEnumerable<string> names) =>
        string.Join(", ", names.Select(JsonText.CSharpLiteral));

    private static string Identifier(string wireName)
    {
        var parts = wireName.Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(part =>
            char.ToUpperInvariant(part[0]) + (part.Length > 1 ? part.Substring(1) : string.Empty)));
    }
}
