using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KJX.Scripting.Codegen;

/// <summary>
/// Generates everything that follows from the <c>[ScriptApi]</c> interfaces in a project: the API
/// descriptor with its content hash, and the dispatch tables that invoke members by wire name
/// without reflecting over their parameters.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ScriptApiGenerator : IIncrementalGenerator
{
    private const string RuntimeMarkerType = "KJX.Scripting.Runtime.IScriptApiDispatcher";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaces = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "KJX.Scripting.ScriptApiAttribute",
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (attributeContext, _) => attributeContext.TargetSymbol as INamedTypeSymbol)
            .Where(static symbol => symbol != null)
            .Collect();

        var rootNamespace = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var value);
            return value;
        });

        var input = context.CompilationProvider.Combine(interfaces).Combine(rootNamespace);

        context.RegisterSourceOutput(input, static (production, values) =>
            Execute(production, values.Left.Left, values.Left.Right, values.Right));
    }

    private static void Execute(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> interfaces,
        string rootNamespace)
    {
        if (interfaces.IsDefaultOrEmpty)
            return;

        if (compilation.GetTypeByMetadataName(RuntimeMarkerType) == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                CodegenDiagnostics.RuntimeNotReferenced,
                interfaces[0].Locations.FirstOrDefault(location => location.IsInSource) ?? Location.None));
            return;
        }

        var generatedNamespace = GeneratedNamespace(rootNamespace, compilation.AssemblyName);

        var model = ApiModelBuilder.Build(compilation, interfaces, generatedNamespace, context.ReportDiagnostic);
        if (model == null || model.Types.Count == 0)
            return;

        var descriptor = DescriptorEmitter.Emit(model);

        Add(context, "ScriptApiDescriptor.g.cs", EmitDescriptorSource(model, descriptor.Json, descriptor.Hash));

        foreach (var file in DispatchEmitter.Emit(model))
            Add(context, file.HintName, file.Source);
    }

    private static void Add(SourceProductionContext context, string hintName, string source) =>
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));

    private static string EmitDescriptorSource(ApiModel model, string json, string hash)
    {
        var code = new CodeBuilder();
        code.Line("// <auto-generated>");
        code.Line("//     Generated by KJX.Scripting.Codegen. The descriptor is the contract clients");
        code.Line("//     fetch on connect; the hash changes exactly when the surface does.");
        code.Line("// </auto-generated>");
        code.Line("#nullable disable");
        code.Line();

        using (code.Block($"namespace {model.GeneratedNamespace}"))
        {
            code.Doc("The scripting API of this assembly, as JSON, with the hash of its contents.");
            using (code.Block("public static class ScriptApiDescriptor"))
            {
                code.Doc("The content hash of the descriptor body.");
                code.Line($"public const string Hash = {JsonText.CSharpLiteral(hash)};");
                code.Line();
                code.Doc("The descriptor: every type, member, parameter, DTO and enum on the surface.");
                code.Line($"public const string Json = {JsonText.CSharpLiteral(json)};");
            }
        }

        return code.ToString();
    }

    /// <summary>
    /// Generated code goes under the project's own root namespace so that two assemblies with a
    /// scripting surface never collide on a type name.
    /// </summary>
    private static string GeneratedNamespace(string rootNamespace, string assemblyName)
    {
        var source = !string.IsNullOrWhiteSpace(rootNamespace) ? rootNamespace : assemblyName;
        if (string.IsNullOrWhiteSpace(source))
            return "ScriptApi.Generated";

        var text = new StringBuilder(source.Length);
        foreach (var character in source)
            text.Append(char.IsLetterOrDigit(character) || character == '_' || character == '.' ? character : '_');

        if (char.IsDigit(text[0]))
            text.Insert(0, '_');

        return text + ".Generated";
    }
}
