/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "firmware.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RequestHeader, RequestHeader, AUTO)


PB_BIND(ResponseHeader, ResponseHeader, AUTO)


PB_BIND(Ack, Ack, AUTO)


PB_BIND(Nack, Nack, AUTO)


PB_BIND(LedControl, LedControl, AUTO)


PB_BIND(GetFirmwareVersions, GetFirmwareVersions, AUTO)


PB_BIND(Ping, Ping, AUTO)


PB_BIND(Pong, Pong, AUTO)


PB_BIND(FirmwareVersions, FirmwareVersions, AUTO)


PB_BIND(Request, Request, AUTO)


PB_BIND(Response, Response, AUTO)









