name: Deploy to releases

on:
  push:
    tags:
      - 'v*'
        
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Print working directory
        run: pwd
        
      - name: Restore source dependencies
        run: dotnet restore ./src
        
      - name: Build package
        run: dotnet build ./src --configuration Release --no-restore
        
      - name: Restore Nuget project dependencies
        run: dotnet restore

      - name: Extract tag version
        id: version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Debug the version
        run: echo "Using version ${{ env.PACKAGE_VERSION }}"
        
      - name: Package project
        run: dotnet pack --no-restore --no-build --configuration Release -o ./nupkgs -p:PackageVersion=${{ env.PACKAGE_VERSION }}

        
      