name: Deploy to releases

on: ['push']
        
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore Dependencies
        run: cd src | dotnet restore
        
      - name: Build package
        run: cd src | dotnet build --configuration Release --no-restore
        
      - name: Package project
        run: dotnet pack --no-restore --no-build --configuration Release
        
      