name: Deploy to releases

on: ['push']
        
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Print working directory
        run: pwd

      - name: Extract version from Git tag
        shell: bash
        run: |
            VERSION="${GITHUB_REF##*/}"
            echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
            echo "✅ Extracted PACKAGE_VERSION=$VERSION"

      - name: Confirm version value
        run: echo "💡 Version for packaging is ${{ env.PACKAGE_VERSION }}"
      
      - name: Debug the version
        run: echo "Using version ${{ env.PACKAGE_VERSION }}"

        
      