name: Deploy to releases

on: ['push']
        
jobs:
  build:
    runs-on: windows-latest
    env:
      PROJECT_PATH: ./src
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Print working directory
        run: pwd
        
      - name: Restore Dependencies
        run: dotnet restore $PROJECT_PATH
        
      - name: Build package
        run: dotnet build $PROJECT_PATH --configuration Release --no-restore
        
      - name: Package project
        run: dotnet pack --no-restore --no-build --configuration Release
        
      